export const teams = [
  {
    id: "modi",
    name: "Team Modi",
    fullName: "Team Modi Visionaries",
    tagline: "Visionary Leadership",
    motto: "Vision Drives Leadership",
    color: "#E67E22",
    colorName: "Orange",
    icon: "lion",
    mascot: "Lion",
    rank: 1,
    points: 1285,
    weekPoints: 685,
    business: "₹98.5L",
    referrals: 156,
    meetings: 312,
    winRate: "100%",
    members: 8,
    owner: {
      id: "narendra-modi",
      name: "Narendra Modi",
      title: "Team Owner & Leader",
      from: "Vadnagar, Gujarat, India",
      experience: "45+ Years",
      focusAreas: "Nation Building, Governance, Innovation, Development",
      leadershipStyle: "Visionary • Decisive • People First",
      quote: "A leader is one who knows the way, goes the way, and shows the way.",
      company: {
        name: "ExampleTech Solutions Pvt. Ltd.",
        industry: "IT Services & Consulting",
        founded: "2012",
        headquarters: "Ahmedabad, Gujarat, India",
        website: "www.exampletech.com",
        size: "50-100 Employees",
        about: "ExampleTech Solutions is a next-generation technology company empowering businesses with innovative digital solutions.",
        values: ["Innovation", "Integrity", "Excellence", "Impact"],
      },
      phone: "+91 98765 43210",
      email: "narendra.modi@example.com",
    },
    description: "Team Modi Visionaries believes in the power of vision, innovation and purposeful action. We focus on creating long-term value, building meaningful relationships and driving progress that leaves a legacy.",
    achievements: [
      { title: "Week 1 Champions", desc: "Dominated the opening week with excellence." },
      { title: "Highest Visitors", desc: "Achieved the highest visitor count in Week 1." },
      { title: "Referral Masters", desc: "Most referrals generated in Week 2." },
      { title: "Consistency Award", desc: "Maintained top performance for 2 weeks." },
    ],
    weeklyMembers: [
      { name: "Rahul Sharma", industry: "Manufacturing", points: 256 },
      { name: "Priya Mehta", industry: "Real Estate", points: 198 },
      { name: "Vikas Agarwal", industry: "Financial Services", points: 176 },
      { name: "Anil Desai", industry: "Logistics", points: 162 },
      { name: "Kunal Patel", industry: "IT Solutions", points: 158 },
      { name: "Neha Singh", industry: "Wellness", points: 142 },
      { name: "Rohit Malhotra", industry: "Marketing", points: 102 },
      { name: "Sameer Khan", industry: "Interiors", points: 91 },
    ],
    performance: {
      visitors: 92,
      referrals: 88,
      tyfcb: 84,
      oneToOnes: 90,
      attendance: 96,
    },
  },
  {
    id: "doval",
    name: "Team Doval",
    fullName: "Team Doval Strategists",
    tagline: "Strategy Intelligence",
    motto: "Strategy Creates Impact",
    color: "#1E3A8A",
    colorName: "Blue",
    icon: "eagle",
    mascot: "Eagle",
    rank: 2,
    points: 1160,
    weekPoints: 592,
    business: "₹86.2L",
    referrals: 132,
    meetings: 268,
    winRate: "50%",
    members: 8,
    owner: {
      id: "ajit-doval",
      name: "Ajit Doval",
      title: "Team Owner & Leader",
      from: "Pauri Garhwal, Uttarakhand, India",
      experience: "40+ Years",
      focusAreas: "Strategy, Intelligence, Security, Leadership",
      leadershipStyle: "Strategic • Precise • Result-Oriented",
      quote: "Strategy without tactics is the slowest route to victory. Tactics without strategy is the noise before defeat.",
      company: {
        name: "StratEdge Consulting Pvt. Ltd.",
        industry: "Business Strategy & Consulting",
        founded: "2010",
        headquarters: "New Delhi, India",
        website: "www.stratedge.com",
        size: "25-50 Employees",
        about: "StratEdge Consulting delivers high-impact strategic solutions that help businesses navigate complex challenges and achieve sustainable growth.",
        values: ["Strategy", "Intelligence", "Precision", "Excellence"],
      },
      phone: "+91 98765 43211",
      email: "ajit.doval@example.com",
    },
    description: "Team Doval Strategists are masters of precision. We combine strategic intelligence with swift execution to outmaneuver competition and build lasting business impact.",
    achievements: [
      { title: "Strategic Excellence", desc: "Highest strategy score in Week 1." },
      { title: "Intelligence Award", desc: "Best analytics and data-driven decisions." },
    ],
    weeklyMembers: [
      { name: "Arjun Kapoor", industry: "Finance", points: 220 },
      { name: "Sita Rao", industry: "Healthcare", points: 185 },
      { name: "Dev Sharma", industry: "Technology", points: 170 },
      { name: "Meera Joshi", industry: "Education", points: 155 },
      { name: "Raj Malhotra", industry: "Retail", points: 140 },
      { name: "Preethi Kumar", industry: "Media", points: 130 },
      { name: "Suresh Verma", industry: "Agriculture", points: 90 },
      { name: "Nisha Patel", industry: "Textiles", points: 70 },
    ],
    performance: {
      visitors: 85,
      referrals: 80,
      tyfcb: 78,
      oneToOnes: 82,
      attendance: 88,
    },
  },
  {
    id: "amit-shah",
    name: "Team Amit Shah",
    fullName: "Team Amit Shah Warriors",
    tagline: "Power Execution",
    motto: "Execution Builds Power",
    color: "#C0392B",
    colorName: "Red",
    icon: "shield",
    mascot: "Shield",
    rank: 3,
    points: 1085,
    weekPoints: 548,
    business: "₹78.4L",
    referrals: 118,
    meetings: 262,
    winRate: "0%",
    members: 7,
    owner: {
      id: "amit-shah",
      name: "Amit Shah",
      title: "Team Owner & Leader",
      from: "Mumbai, Maharashtra, India",
      experience: "35+ Years",
      focusAreas: "Power, Execution, Leadership, Business Growth",
      leadershipStyle: "Decisive • Courageous • Action-Oriented",
      quote: "Courage is not the absence of fear. It is taking action in spite of it.",
      company: {
        name: "PowerBuild Industries Pvt. Ltd.",
        industry: "Infrastructure & Construction",
        founded: "2008",
        headquarters: "Ahmedabad, Gujarat, India",
        website: "www.powerbuild.com",
        size: "100-500 Employees",
        about: "PowerBuild Industries creates world-class infrastructure solutions that power India's growth engine.",
        values: ["Strength", "Execution", "Courage", "Victory"],
      },
      phone: "+91 98765 43212",
      email: "amit.shah@example.com",
    },
    description: "Team Amit Shah Warriors thrive under pressure. With unmatched execution power and warrior spirit, we turn every challenge into a victory.",
    achievements: [
      { title: "Execution Excellence", desc: "Best execution rate in Week 2." },
    ],
    weeklyMembers: [
      { name: "Vijay Singh", industry: "Real Estate", points: 210 },
      { name: "Asha Gupta", industry: "Manufacturing", points: 190 },
      { name: "Kiran Desai", industry: "Construction", points: 165 },
      { name: "Manoj Tiwari", industry: "Retail", points: 150 },
      { name: "Sunita Jain", industry: "Hospitality", points: 135 },
      { name: "Harish Rao", industry: "Transport", points: 125 },
      { name: "Deepa Nair", industry: "Healthcare", points: 110 },
    ],
    performance: {
      visitors: 80,
      referrals: 75,
      tyfcb: 72,
      oneToOnes: 78,
      attendance: 82,
    },
  },
  {
    id: "jaishankar",
    name: "Team Jaishankar",
    fullName: "Team Jaishankar Diplomats",
    tagline: "Diplomacy Global Impact",
    motto: "Diplomacy Expands Horizons",
    color: "#27AE60",
    colorName: "Green",
    icon: "🪷",
    mascot: "Lotus",
    rank: 4,
    points: 970,
    weekPoints: 486,
    business: "₹65.3L",
    referrals: 104,
    meetings: 236,
    winRate: "0%",
    members: 7,
    owner: {
      id: "s-jaishankar",
      name: "Dr. S. Jaishankar",
      title: "Team Owner & Leader",
      from: "New Delhi, India",
      experience: "38+ Years",
      focusAreas: "Diplomacy, Global Relations, Business Development, Strategy",
      leadershipStyle: "Diplomatic • Articulate • Global Thinker",
      quote: "Every relationship is an opportunity. Every connection builds a bridge to something greater.",
      company: {
        name: "GlobalBridge Ventures Pvt. Ltd.",
        industry: "International Trade & Consulting",
        founded: "2015",
        headquarters: "New Delhi, India",
        website: "www.globalbridge.com",
        size: "20-50 Employees",
        about: "GlobalBridge Ventures connects Indian businesses with global markets through strategic partnerships and diplomatic excellence.",
        values: ["Diplomacy", "Relations", "Harmony", "Growth"],
      },
      phone: "+91 98765 43213",
      email: "s.jaishankar@example.com",
    },
    description: "Team Jaishankar Diplomats expand possibilities through collaboration and strategic relationships. We build bridges that create lasting value for businesses and communities.",
    achievements: [
      { title: "Networking Champion", desc: "Most new connections established." },
    ],
    weeklyMembers: [
      { name: "Ankit Verma", industry: "Export", points: 200 },
      { name: "Riya Sharma", industry: "Import", points: 175 },
      { name: "Sameer Patel", industry: "Consulting", points: 150 },
      { name: "Kavita Rao", industry: "Hospitality", points: 140 },
      { name: "Amit Gupta", industry: "Tourism", points: 120 },
      { name: "Sneha Joshi", industry: "Education", points: 100 },
      { name: "Rahul Nair", industry: "IT", points: 85 },
    ],
    performance: {
      visitors: 75,
      referrals: 70,
      tyfcb: 68,
      oneToOnes: 72,
      attendance: 78,
    },
  },
];

export const weeklyEvents = [
  {
    week: 1,
    dates: "Jun 24 – Jun 30",
    theme: "STRONG START. STRONGER IMPACT.",
    description: "Kickstarting the league with focus, energy and meaningful connections.",
    events: [
      { name: "Opening Ceremony", category: "Ceremony", points: 50, status: "completed" },
      { name: "Business Growth Sprint", category: "Networking", points: 100, status: "completed" },
      { name: "Refer & Earn Challenge", category: "Referrals", points: 150, status: "in-progress" },
      { name: "TYFCB Challenge", category: "TYFCB", points: 100, status: "in-progress" },
      { name: "One-to-One Blitz", category: "Meetings", points: 100, status: "upcoming" },
      { name: "Attendance Booster", category: "Attendance", points: 75, status: "upcoming" },
    ],
  },
  {
    week: 2,
    dates: "Jul 1 – Jul 7",
    theme: "THE CONNECT CHALLENGE",
    description: "Building connections. Creating opportunities. Driving the nation forward.",
    events: [
      { name: "Mega Referral Drive", category: "Referrals", points: 200, status: "upcoming" },
      { name: "Leadership Showcase", category: "Leadership", points: 150, status: "upcoming" },
      { name: "Business Impact Sprint", category: "Business", points: 175, status: "upcoming" },
      { name: "Team Collaboration", category: "Teamwork", points: 125, status: "upcoming" },
    ],
  },
  {
    week: 3,
    dates: "Jul 8 – Jul 14",
    theme: "RISE TO THE TOP",
    description: "Intensify the competition and push beyond limits.",
    events: [
      { name: "Mid-League Summit", category: "Special Event", points: 250, status: "upcoming" },
      { name: "Power Networking", category: "Networking", points: 175, status: "upcoming" },
      { name: "Revenue Drive", category: "Business", points: 200, status: "upcoming" },
    ],
  },
  {
    week: 4,
    dates: "Jul 15 – Jul 22",
    theme: "THE FINAL BATTLE",
    description: "Everything is on the line. Champions are made in the final stretch.",
    events: [
      { name: "Leaders Connect", category: "Special Event", points: 200, status: "upcoming" },
      { name: "Grand Finale Sprint", category: "Business", points: 300, status: "upcoming" },
      { name: "Finale & Awards Night", category: "Ceremony", points: 100, status: "upcoming" },
    ],
  },
];

export const specialEvents = [
  {
    name: "Opening Ceremony",
    desc: "The grand opening of ARES Business League 2026. Let the legacy begin!",
    date: "Jul 24, 2026",
    time: "6:00 PM",
    status: "upcoming",
  },
  {
    name: "Mid-League Summit",
    desc: "Strategy. Connect. Grow. A power-packed mid-league event.",
    date: "Jul 03, 2026",
    time: "6:00 PM",
    status: "upcoming",
  },
  {
    name: "Leaders Connect",
    desc: "Exclusive networking evening for leaders and changemakers.",
    date: "Jul 10, 2026",
    time: "6:00 PM",
    status: "upcoming",
  },
  {
    name: "Finale & Awards Night",
    desc: "The ultimate showdown and celebration of champions.",
    date: "Jul 22, 2026",
    time: "6:00 PM",
    status: "upcoming",
  },
];

export const partners = [
  { name: "ACME Corporate Solutions", tier: "Platinum Partner", tagline: "Innovate • Collaborate • Elevate" },
  { name: "BNI", tier: "Strategic Partner", tagline: "Better Together" },
  { name: "Kapstone", tier: "Gold Partner", tagline: "Integrated Solutions" },
  { name: "GiFT", tier: "Gifting Partner", tagline: "Gifting Partner" },
  { name: "PrintVista", tier: "Print Partner", tagline: "Print Partner" },
  { name: "The Logo Co", tier: "Branding Partner", tagline: "Branding Partner" },
  { name: "WebHance", tier: "Digital Partner", tagline: "Digital Partner" },
  { name: "Digital 360", tier: "Marketing Partner", tagline: "360° Marketing" },
];

export const blogPosts = [
  {
    id: "power-of-strategic-collaboration",
    title: "The Power of Strategic Collaboration",
    excerpt: "How strategic partnerships create exponential value in business and beyond. Discover why the most successful businesses in ABL 2026 are the ones that master the art of collaboration.",
    author: "Team Modi",
    date: "May 29, 2026",
    readTime: "4 min read",
    category: "Strategy",
  },
  {
    id: "leadership-in-the-arena",
    title: "Leadership in the Arena: Key Takeaways",
    excerpt: "Lessons from Week 1 that are shaping the champions of tomorrow. How decisive leadership under pressure is the defining trait of top performers this season.",
    author: "Team Doval",
    date: "May 27, 2026",
    readTime: "5 min read",
    category: "Leadership",
  },
  {
    id: "building-connections",
    title: "Building Connections, Building the Nation",
    excerpt: "Every referral, every meeting, every connection counts towards a greater purpose. This week's challenge is showing us how business relationships fuel national growth.",
    author: "Team Jaishankar",
    date: "May 25, 2026",
    readTime: "3 min read",
    category: "Networking",
  },
  {
    id: "execution-is-everything",
    title: "Execution is Everything: Week 2 Insights",
    excerpt: "Strategy is nothing without execution. Our warriors are proving that discipline, consistency, and relentless action separate the good from the legendary.",
    author: "Team Amit Shah",
    date: "May 24, 2026",
    readTime: "4 min read",
    category: "Execution",
  },
];

export const commissioners = [
  { name: "R. K. Sharma", role: "Chief Commissioner", desc: "Upholding integrity and excellence." },
  { name: "Neha Verma", role: "Operations Commissioner", desc: "Ensuring smooth operations and seamless execution." },
  { name: "Vikram Singh", role: "Compliance Commissioner", desc: "Ensuring fair play and rule adherence." },
  { name: "Arjun Mehta", role: "Engagement Commissioner", desc: "Building connections and growing the league community." },
  { name: "Pooja Iyer", role: "Growth Commissioner", desc: "Driving growth, partnerships and opportunities." },
  { name: "Karan Malhotra", role: "Technology Commissioner", desc: "Leveraging technology for transparency and innovation." },
];

export const tournamentRules = [
  {
    section: "Scoring System",
    rules: [
      "Business Growth (TYFCB): Up to 300 points per week",
      "Referrals Generated: Up to 250 points per week",
      "Meetings Conducted: Up to 200 points per week",
      "One-to-Ones: Up to 150 points per week",
      "Event Participation: Up to 100 points per week",
      "Maximum 1,000 core points per week",
    ],
  },
  {
    section: "Bonus Points",
    rules: [
      "Early Bird Bonus: +25 points (complete events before deadline)",
      "Perfect Week Bonus: +100 points (complete all events in a week)",
      "Consistency Bonus: +75 points (participate in 5+ consecutive events)",
      "Mega Impact Bonus: +150 points (generate high business impact)",
      "Maximum 350 bonus points per week",
    ],
  },
  {
    section: "Deductions",
    rules: [
      "No Show: -25 points (missed event without notice)",
      "Late Submission: -15 points (submitted after deadline)",
      "Incomplete Activity: -10 points (did not meet event requirements)",
    ],
  },
  {
    section: "Eligibility",
    rules: [
      "All participants must be active BNI members",
      "Each team has 7-8 business owners",
      "Participants must attend minimum 75% of events",
      "Business data must be verified by chapter leadership",
    ],
  },
  {
    section: "Tournament Format",
    rules: [
      "Duration: June 24 to July 22, 2026 (4 weeks)",
      "Weekly themes guide each week's challenges",
      "Leaderboard updated every Wednesday at 8:00 PM",
      "Final standings determine the champion",
    ],
  },
  {
    section: "Prize & Recognition",
    rules: [
      "Winning team owner receives 1.5x prize pool",
      "Individual MVP awards for top performers",
      "Team trophies for champion and runner-up",
      "Permanent Wall of Fame recognition",
    ],
  },
];
