import { Team, WeeklyEvent, SpecialEvent, Partner, BlogPost, RuleSection, ScheduleEvent } from "@/types";

export const teams: Team[] = [
  {
    id: "modi",
    name: "Advocate Jay Visionaries",
    fullName: "Advocate Jay Visionaries - Team Modi",
    tagline: "Visionary Leadership",
    motto: "Vision Drives Leadership",
    color: "#FF8C00",
    colorName: "Orange",
    icon: "lion",
    mascot: "Lion",
    rank: 1,
    points: 123927,
    weekPoints: 65550,
    business: "--",
    referrals: 0,
    meetings: 0,
    visitors: 0,
    induction: 0,
    winRate: "0%",
    members: 7,
    owner: {
      id: "jay-patel",
      name: "Advocate Jay Patel",
      image: "/images/owner_modi.png",
      title: "Team Owner & Leader",
      from: "Gujarat, India",
      experience: "15+ Years",
      focusAreas: "Family & Property Disputes, Revenue Cases, Money Recovery, Cheque Return Cases",
      leadershipStyle: "Visionary • Strategic • Ethical",
      quote: "Justice and vision are the bedrock of true leadership.",
      company: {
        name: "Jay G Patel - Advocate",
        industry: "Legal Services",
        founded: "2008",
        headquarters: "Ahmedabad, Gujarat, India",
        website: "www.advocatejaypatel.com",
        size: "2-3 Employees",
        about: "With over 15 years of dedicated legal practice and more than 200 successful matters across Gujarat's courts, Advocate Jay Patel brings sharp legal acumen, deep procedural knowledge, and a results-driven mindset to every case. His practice spans criminal defence, civil litigation, family disputes, land revenue matters, and financial crime cases, making him one of the most versatile trial advocates practising across Ahmedabad and Gandhinagar today.",
        values: ["Result Oriented", "Confidential & Transparent", "Proven Results", "Client Focused"],
        connectWith: ["Corporates & Businesses", "Individuals & Families", "Property Owners & Developers", "Financial Institutions & Banks", "Other Advocates & CAs", "HR & Compliance Teams"],
        services: [
          { icon: "gavel", name: "Criminal Cases", desc: "Full-spectrum criminal defence & trial advocacy." },
          { icon: "key", name: "Bail Matters", desc: "Regular, anticipatory & High Court bail applications." },
          { icon: "users", name: "Family Matters", desc: "Matrimonial, custody & succession disputes." },
          { icon: "heart-crack", name: "Divorce Cases", desc: "Contested & mutual consent divorce proceedings." },
          { icon: "map", name: "Land Disputes", desc: "Title, encroachment & partition litigation." },
          { icon: "landmark", name: "Land Revenue Cases", desc: "Revenue tribunal appeals & tenancy matters." },
          { icon: "banknote", name: "Money Recovery Suits", desc: "Civil recovery through summary & plaint proceedings." },
          { icon: "receipt", name: "Cheque Return Matters", desc: "Section 138 NI Act enforcement & defence." },
        ],
      },
      phone: "+91 99987 14891",
      email: "jay1802@gmail.com",
    },
    description: "Team Modi Visionaries believes in the power of vision, innovation and purposeful action. We focus on creating long-term value, building meaningful relationships and driving progress that leaves a legacy.",
    achievements: [
      { title: "Week 1 Champions", desc: "Dominated the opening week with excellence." },
      { title: "Highest Visitors", desc: "Achieved the highest visitor count in Week 1." },
      { title: "Referral Masters", desc: "Most referrals generated in Week 2." },
      { title: "Consistency Award", desc: "Maintained top performance for 2 weeks." },
    ],
    weeklyMembers: [
      { name: "Simran Vatyani", image: "/images/roster/simran-vatyani.png", industry: "Interior Design", points: 1100, company: "SV Space Designs", companyDesc: "Interior design studio serving builders, contractors, real estate developers and architects.", product: "Interior Design", category: "Interior Designer", idealConnect: "Builders & Contractors, Real Estate Developers, Architects, Turnkey Interior Designers" },
      { name: "Rohan Shah", image: "/images/roster/rohan-shah.png", industry: "UPVC/Aluminium Doors & Windows", points: 10055, company: "Preetam Poly Windows", companyDesc: "UPVC and aluminium doors and windows for architects, contractors and builders.", product: "UPVC/Aluminium Doors & Windows", category: "UPVC/Aluminium Doors & Windows", idealConnect: "Architects & Interior Designers, PMC, Contractors, Builders" },
      { name: "Ankit Patel", image: "/images/roster/ankit-patel.png", industry: "Foreign Exchange", points: 4210, company: "Prihaan Financial Services", companyDesc: "Foreign exchange services for overseas students, international travellers and families travelling abroad.", product: "Foreign Exchange", category: "Foreign Exchange", idealConnect: "Overseas Student Consultants, International Travel Operators, Families Travelling Abroad" },
      { name: "Sujal Soni", image: "/images/roster/sujal-soni.png", industry: "International Tours & Travel", points: 1700, company: "Destination Anywhere Travel Co.", companyDesc: "International tours and travel company serving families, corporates, wedding planners and honeymooners.", product: "International Tours & Travel", category: "International Tours & Travel", idealConnect: "Friends and Family Travelling Abroad, Corporates, Wedding Planners, Honeymooners" },
      { name: "Rushil Pandya", image: "/images/roster/rushil-pandya.png", industry: "Health Coaching", points: 5725, company: "Fitness Hustler", companyDesc: "Health coaching for gym owners, fitness enthusiasts and Gujarati businessmen aged 25-40.", product: "Health Coaching", category: "Health Coach", idealConnect: "Gym Owners, Gujarati Businessmen (25-40 age), Fitness Enthusiasts" },
      { name: "Samarth Sisodiya", image: "/images/roster/samarth-sisodia.png", industry: "Media Services", points: 4995, company: "7 Elements", companyDesc: "Media services agency working with business owners, product-based companies, and marketing and branding agencies.", product: "Media Services", category: "Media Services", idealConnect: "Business Owners, Product-based Companies, Marketing and Branding Agencies" },
    ],
    performance: {
      visitors: 0,
      referrals: 0,
      tyfcb: 0,
      oneToOnes: 0,
      attendance: 0,
    },
    superpower: {
      name: "MASTERSTROKE",
      description: "Select one player from your team. All points scored by that selected player during the week - you will get 2X bonus points.",
      iconName: "Target",
    },
    totalPointsSpent: 128000,
  },
  {
    id: "doval",
    name: "Silver Spoon Warriors",
    fullName: "Silver Spoon Warriors - Team Doval",
    tagline: "Strategy Intelligence",
    motto: "Strategy Creates Impact",
    color: "#3B82F6",
    colorName: "Blue",
    icon: "eagle",
    mascot: "Eagle",
    rank: 2,
    points: 87110,
    weekPoints: 30890,
    business: "₹55,68,710",
    referrals: 32,
    meetings: 59,
    visitors: 1,
    induction: 0,
    winRate: "0%",
    members: 7,
    owner: {
      id: "vishnu-soni",
      name: "Vishnu Soni",
      image: "/images/owner_doval.png",
      title: "Team Owner & Leader",
      from: "Gujarat, India",
      experience: "20+ Years",
      focusAreas: "Silver Jewelry, Giftware, Corporate Gifting",
      leadershipStyle: "Strategic • Customer-Centric",
      quote: "Creating experiences that leave a lasting impression.",
      company: {
        name: "Silver Spoon",
        industry: "Silver Jewelry & Giftware",
        founded: "2019",
        headquarters: "Ahmedabad, Gujarat, India",
        website: "www.silverspoonbyacj.com",
        size: "50-100 Employees",
        about: "Silver Spoon is an Ahmedabad-based silver jewellery and gifting brand, crafting premium 925 sterling and 999 fine silver pieces since 2019. Rooted in Indian craftsmanship and heritage design, we specialize in hallmark-certified silver jewellery, silverware, and pooja essentials — blending traditional artistry with contemporary style. From everyday wear to festive and gifting occasions, every piece we create reflects purity, precision, and trust.",
        values: ["Craftsmanship", "Purity", "Heritage", "Trust"],
        connectWith: [
          "Retailers & Distributors of Certified Silver Jewellery",
          "Corporate Gifting Partners — HR Teams & Event Planners",
          "Wedding & Event Planners — Bulk Gifting & Trousseau",
          "Retail/Boutique Owners — Jewellery, Decor & Spiritual Products",
          "B2B Bulk Buyers — White-Labeled & Co-Branded Collections",
          "Individual Customers Seeking Certified Purity & Craftsmanship",
        ],
        services: [
          { icon: "gem", name: "Silver Jewellery", desc: "Rings, chains, bracelets, kadas, anklets & mangalsutra for men and women." },
          { icon: "sparkles", name: "German Silver Items", desc: "German silver & silver-coated decorative and gifting pieces." },
          { icon: "utensils", name: "Silverware & Tableware", desc: "Silverware and tableware crafted for home and gifting." },
          { icon: "landmark", name: "Pooja & Spiritual Idols", desc: "Silver idols and pooja essentials rooted in Indian tradition." },
          { icon: "frame", name: "Silver Photo Frames", desc: "Hallmark-certified silver photo frames for keepsakes and gifting." },
          { icon: "pin", name: "Brooches", desc: "Silver brooches blending traditional artistry with contemporary style." },
          { icon: "gift", name: "Rakhi Collection", desc: "Seasonal silver Rakhi collection dropped weekly as new arrivals." },
        ],
      },
      phone: "+91 99981 23479",
      email: "vnu444@gmail.com",
    },
    description: "Team Doval Strategists are masters of precision. We combine strategic intelligence with swift execution to outmaneuver competition and build lasting business impact.",
    achievements: [
      { title: "Strategic Excellence", desc: "Highest strategy score in Week 1." },
      { title: "Intelligence Award", desc: "Best analytics and data-driven decisions." },
    ],
    weeklyMembers: [
      { name: "Yash Thakkar", image: "/images/roster/yash-thakkar.png", industry: "Plywood & Laminates", points: 620, company: "Vee Decor", companyDesc: "Plywood and laminates supplier serving architects, interior designers, bungalow owners, PMC and civil engineers.", product: "Plywood & Laminates", category: "Plywood & Laminates", idealConnect: "Architects, Interior Designer, Bungalow Owner, PMC, Civil Engineer" },
      { name: "Sunil Agrawal", image: "/images/roster/sunil-agrawal.png", industry: "Ceramic Tiles", points: 1930, company: "Krishna Ceramic", companyDesc: "Ceramic tiles supplier serving architects, interior designers, bungalow owners, PMC and civil engineers.", product: "Ceramic Tiles", category: "Ceramic Tiles", idealConnect: "Architects, Interior Designer, Bungalow Owner, PMC, Civil Engineer" },
      { name: "Ashutosh Mehta", image: "/images/roster/ashutosh-mehta.png", industry: "MEP Contracting", points: 5250, company: "ShyamRatna Projects", companyDesc: "MEP contracting firm serving civil contractors, builders, real estate developers, architects and RMC/PMC teams.", product: "MEP Contracting", category: "MEP Contracting", idealConnect: "Civil Contractor, Builders, Real Estate Developer, Architects, RMC/PMC" },
      { name: "Jigar R Shah", image: "/images/roster/jigar-shah.png", industry: "Air Ticket, Passport & Visa", points: 12230, company: "Jade Tours & Travels", companyDesc: "Air ticket, passport and visa services for friends and family travelling abroad, honeymooners and wedding planners.", product: "Air Ticket, Passport & Visa", category: "Air Ticket, Passport & Visa", idealConnect: "Friends and Family Travelling Abroad, Honeymooners, Friends & Families, Wedding Planners" },
      { name: "Dhaval Thakor", image: "/images/roster/dhaval-thakor.png", industry: "Event Planning", points: 3910, company: "Club MJ Events", companyDesc: "Event planning services for corporates, wedding planners, hotels/resorts/banquet halls and educational institutions.", product: "Event Planning", category: "Event Planner", idealConnect: "Corporates, Wedding Planners, Hotel/Resorts/Banquet Halls, Educational Institution" },
      { name: "Vishva Ambasana", image: "/images/roster/vishva-ambasana.png", industry: "AI Tool Development", points: 2220, company: "Hybrid StudioZ", companyDesc: "AI tool development for business owners, manufacturers, IT companies, FMCG brands and hospital chains.", product: "AI Tool Development", category: "AI Tool Development", idealConnect: "Business Owners, Manufacturers, IT Companies, FMGC Brands, Hospital Chain" },
    ],
    performance: {
      visitors: 0,
      referrals: 0,
      tyfcb: 0,
      oneToOnes: 0,
      attendance: 0,
    },
    superpower: {
      name: "OPERATION CHANAKYA",
      description: "Choose any 2 categories from any two competing team(s). For that week, your team will earn bonus of 2X the points scored by those teams in the selected 2 categories.",
      iconName: "TowerControl",
    },
    totalPointsSpent: 424000,
  },
  {
    id: "amit-shah",
    name: "Vaer Strategists",
    fullName: "Vaer Strategists - Team Amit Shah",
    tagline: "Power Execution",
    motto: "Execution is Everything",
    color: "#EF4444",
    colorName: "Red",
    icon: "tiger",
    mascot: "Tiger",
    rank: 4,
    points: 49310,
    weekPoints: 18800,
    business: "--",
    referrals: 0,
    meetings: 0,
    visitors: 0,
    induction: 0,
    winRate: "0%",
    members: 7,
    owner: {
      id: "harsh-brambhatt",
      name: "Harsh Brambhatt",
      image: "/images/owner_shah.png",
      title: "Team Owner & Leader",
      from: "Gujarat, India",
      experience: "12+ Years",
      focusAreas: "Execution, Operations, Climate Control",
      leadershipStyle: "Action-Oriented • Decisive",
      quote: "Execution is the key to maintaining the perfect environment.",
      company: {
        name: "Vaer HVAC Solutions",
        industry: "HVAC & Engineering",
        founded: "2017",
        headquarters: "Ahmedabad, Gujarat, India",
        website: "www.vaerhvac.com",
        size: "0-10 Employees",
        about: "VAER HVAC is a precision HVAC engineering firm based in Ahmedabad, delivering premium climate control solutions since 2017. We don't just install air conditioning — we engineer complete climate ecosystems, bridging complex architectural vision with high-performance technical execution. With 500+ projects completed, a team of 25+ expert engineers, and 30+ years of industry excellence, we specialize in VRF systems, ducting, and retrofit solutions for luxury residential and commercial spaces. We work with leading brands like Daikin, Carrier, Mitsubishi, Voltas, Blue Star, LG, Hitachi, O General, Samsung, and Panasonic.",
        values: ["Reliability", "Efficiency", "Innovation", "Execution"],
        connectWith: [
          "Architects & Interior Designers — Luxury Residential & Commercial",
          "Builders & Developers — Villas, Penthouses & Commercial Complexes",
          "Corporate & Institutional Clients — Offices, Tech Parks & Factories",
          "Facility & Property Managers — AMC for Existing Systems",
          "Homeowners of Private Bungalows & Residences",
          "Hospitality & F&B — Cafes, Restaurants, Malls & Recreational Spaces",
          "Industrial Clients — Ventilation & Large-Capacity Systems",
        ],
        services: [
          { icon: "wind", name: "Precision VRF Installation", desc: "Heat load calculation, zoned cooling & concealed ducting for luxury homes and offices." },
          { icon: "shield-check", name: "Annual Maintenance (AMC)", desc: "Quarterly deep cleaning, gas level checks and priority support." },
          { icon: "wrench", name: "Rapid Repair & Service", desc: "24/7 emergency support, genuine spares and technical diagnostics." },
          { icon: "refresh-cw", name: "Retrofit & Upgrade", desc: "System audits and energy-efficiency retrofits for aging HVAC infrastructure." },
        ],
      },
      phone: "+91 98246 53242",
      email: "info@vaerhvac.com",
    },
    description: "Team Amit Shah Warriors thrive under pressure. With unmatched execution power and warrior spirit, we turn every challenge into a victory.",
    achievements: [
      { title: "Execution Excellence", desc: "Best execution rate in Week 2." },
    ],
    weeklyMembers: [
      { name: "Shruti Agrawal", image: "/images/roster/shruti-agarwal.png", industry: "Furniture Manufacturing", points: 1920, company: "Arcedior International Pvt. Ltd.", companyDesc: "Furniture manufacturer serving interior designers, hoteliers, builders, home stylists and corporates making new offices.", product: "Furniture Manufacturing", category: "Furniture Manufacturer", idealConnect: "Interior Designers, Hoteliers, Builders, Home Stylists, Corporates Making New Office" },
      { name: "Dr. Chahana Shah", image: "/images/roster/chahana-shah.png", industry: "Dentistry", points: 1330, companyLogo: "/images/roster/chahana-dental-logo.png", company: "Chahana Dental Studio", companyDesc: "Dental studio serving families, corporates and anyone looking to improve oral health.", product: "Dentistry", category: "Dentist", idealConnect: "Families, Corporates, Anyone Looking to Improve Oral Health" },
      { name: "Ankit Jani", image: "/images/roster/ankit-jani.png", industry: "Digital Marketing", points: 890, company: "Jukebox Media Pvt Ltd", companyDesc: "Digital marketing agency helping businesses fix their marketing and increase sales.", product: "Digital Marketing", category: "Digital Marketing", idealConnect: "Businesses Looking to Fix Their Digital Marketing, Businesses Looking to Increase Their Sales" },
      { name: "Het Patel", image: "/images/roster/het-patel.png", industry: "Construction Chemicals", points: 1040, company: "Konek Construction Chemicals", companyDesc: "Construction chemicals supplier serving architects, structural consultants, PMC, builders/developers and bungalow owners.", product: "Construction Chemicals", category: "Construction Chemicals", idealConnect: "Architects, Structural Consultants & PMC, Builders/Developers, Bungalow Owners, Tiles and Marble Showroom Owners" },
      { name: "Varun Bagaria", image: "/images/roster/varun-bagaria.png", industry: "Men's Clothing", points: 950, company: "Prestine", companyDesc: "Men's clothing brand serving hotel owners, corporate offices, wedding planners, grooms and government offices.", product: "Men's Clothing", category: "Men's Clothing", idealConnect: "Hotel Owners, Corporate Offices, Wedding Planers, Grooms, Gov. Offices Looking for Uniforms" },
      { name: "Nitin Upadhyay", image: "/images/roster/nitin-upadhyay.png", industry: "Real Estate", points: 180, company: "Shree Krishna Developer", companyDesc: "Residential plots in Dholera for NRIs, HNIs and land investors.", product: "Residential Plots in Dholera", category: "Residential Plots in Dholera", idealConnect: "NRI's & HNI's, People Looking to Invest in Land, Builders, Architects" },
    ],
    performance: {
      visitors: 0,
      referrals: 0,
      tyfcb: 0,
      oneToOnes: 0,
      attendance: 0,
    },
    superpower: {
      name: "OPERATION LOTUS",
      description: "Choose any player from any competing team - and you get bonus of 2X the points that player scores in that week.",
      iconName: "Flower2",
    },
    totalPointsSpent: 131000,
  },
  {
    id: "jaishankar",
    name: "CSM Diplomats",
    fullName: "CSM Diplomats - Team Jaishankar",
    tagline: "Diplomacy Global Impact",
    motto: "Global Impact, Local Roots",
    color: "#22C55E",
    colorName: "Green",
    icon: "🪷",
    mascot: "Lotus",
    rank: 3,
    points: 62785,
    weekPoints: 45010,
    business: "--",
    referrals: 0,
    meetings: 0,
    visitors: 0,
    induction: 0,
    winRate: "0%",
    members: 7,
    owner: {
      id: "mayursinh-chavda",
      name: "Mayursinh Chavda",
      image: "/images/owner_jaishankar.png",
      title: "Team Owner & Leader",
      from: "Gujarat, India",
      experience: "18+ Years",
      focusAreas: "Accounting, Taxation, Audit & Business Advisory",
      leadershipStyle: "Diplomatic • Collaborative",
      quote: "Building bridges through expert counsel and strategic partnerships.",
      company: {
        name: "CSM & CO LLP",
        industry: "CA & Tax Advisory",
        founded: "2008",
        headquarters: "Ahmedabad, Gujarat, India",
        website: "www.csmllp.com",
        size: "10-50 Employees",
        about: "CSM & Co LLP is a multi-city Chartered Accountancy firm with offices in Ahmedabad and Rajkot, led by four partners. We work with clients across manufacturing, FMCG, service industries, and Public Sector Units — helping them stay compliant, yes, but more importantly, helping them make sharper business decisions.",
        values: ["Diplomacy", "Trust", "Expertise", "Growth"],
        logo: "/images/csm-llp-logo.png",
        connectWith: ["Manufacturing & FMCG Business Owners", "Growing Service Businesses", "Company Secretaries", "Lawyers", "Bankers", "Insurance Advisors"],
        services: [
          { icon: "book-open", name: "Accounting & Bookkeeping", desc: "Accurate books, always audit-ready." },
          { icon: "receipt", name: "Income Tax Services", desc: "Planning, filing & representation." },
          { icon: "file-text", name: "GST Services", desc: "Registration, returns & compliance." },
          { icon: "shield-check", name: "Audit & Assurance", desc: "Statutory, internal & tax audits." },
          { icon: "building", name: "Company & LLP Compliance", desc: "ROC filings & secretarial support." },
          { icon: "briefcase", name: "Business Advisory", desc: "Strategic guidance for growth." },
          { icon: "globe", name: "US Accounting & Tax Outsourcing", desc: "Cross-border bookkeeping & filings." },
          { icon: "file-check", name: "Registration & Compliances", desc: "Business setup & regulatory filings." },
        ],
      },
      phone: "+91 82091 05955",
      email: "mayursinh@csmllp.in",
    },
    description: "Team Jaishankar Diplomats expand possibilities through collaboration and strategic relationships. We build bridges that create lasting value for businesses and communities.",
    achievements: [
      { title: "Networking Champion", desc: "Most new connections established." },
    ],
    weeklyMembers: [
      { name: "Jimil Shah", image: "/images/roster/jimil-shah.png", industry: "Industrial Automation", points: 930, company: "Prio Technology", companyDesc: "Industrial automation for pharma equipment, textile equipment, automobile dealers/manufacturers and industrial traders.", product: "Industrial Automation", category: "Industrial Automation", idealConnect: "Pharma Equipment, Textile Equipment & Automobile Dealers & Manufacturers, Industrial Traders" },
      { name: "Priyank Vora", image: "/images/roster/priyank-vora.png", industry: "Wealth Management", points: 465, company: "Kinstugii Wealth", companyDesc: "Wealth management firm helping individuals and businesses grow and protect their wealth.", product: "Wealth Management", category: "Wealth Management", idealConnect: "Business Owners, HNIs, Families Planning Their Finances" },
      { name: "Rajvi Prajapati", image: "/images/roster/rajvi-prajapati.png", industry: "Manufacturing", points: 2140, company: "SAS Power Semiconductor", companyDesc: "Manufacturer serving furnace, generator and AC/DC drive manufacturers.", product: "Manufacturing", category: "Manufacturing", idealConnect: "Furnace Mfg's, Generator Mfg's, AC/DC Drive Mfg's" },
      { name: "Minakshi Bhavsar", image: "/images/roster/minakshi-bhavsar.png", industry: "Fire & Safety", points: 0, company: "Angel Marketing", companyDesc: "Fire & safety solutions with NOC for builders, architects, hospitals and school admins.", product: "Fire & Safety Solutions with NOC", category: "Fire & Safety Solutions with NOC", idealConnect: "Builder, Architects, Hospitals, School Admin, For Fire Safety NOC" },
      { name: "Sarthak Patel", image: "/images/roster/sarthak-patel.png", industry: "Domestic Travel", points: 1430, company: "Umiya Travel Hub", companyDesc: "Domestic travel agency serving families going on trips, honeymooners, corporates and friends planning getaways.", product: "Domestic Travel", category: "Domestic Travel", idealConnect: "Families Going on Trips, Honeymooners, Corporates, Friends Planning Getaways" },
      { name: "Devarsh Vyas", image: "/images/roster/devarsh-vyas.png", industry: "Power Generators", points: 1060, company: "Ramp Technomation", companyDesc: "Business power generators for architects, MEP consultants and contractors, and industry designers.", product: "Business Power Generator", category: "Business Power Generator", idealConnect: "Architects, MEP Consultants and Contractors, Industry Designers" },
    ],
    performance: {
      visitors: 0,
      referrals: 0,
      tyfcb: 0,
      oneToOnes: 0,
      attendance: 0,
    },
    superpower: {
      name: "GLOBAL OUTREACH",
      description: "For one week, visitor that your team brings - you'll get 2X points for that in bonus points.",
      iconName: "Globe2",
    },
    totalPointsSpent: 190000,
  },
];

export const weeklyEvents: WeeklyEvent[] = [
  {
    week: 1,
    dates: "Jul 1 – Jul 7",
    theme: "STRONG START. STRONGER IMPACT.",
    description: "Kickstarting the league with focus, energy and meaningful connections.",
    events: [
      { name: "121 Conclave – Cross Chapter", category: "121", points: 250, status: "completed", date: "Jul 4, 2026" },
      { name: "Offline Team Meeting", category: "Attendance", points: 250, status: "completed" },
    ],
  },
  {
    week: 2,
    dates: "Jul 8 – Jul 14",
    theme: "THE CONNECT CHALLENGE",
    description: "Building connections. Creating opportunities. Driving the nation forward.",
    events: [
      { name: "Cross Chapter Meet", category: "Networking", points: 0, status: "upcoming", date: "Jul 9, 2026", time: "4:00 PM – 6:00 PM", venue: "Grill Kitchen, Prahladnagar" },
      { name: "Sports Event", category: "Fun & Games", points: 0, status: "upcoming", date: "Jul 10, 2026", time: "8:30 PM onwards" },
      { name: "Know Your Members – Adv. Jay Patel & Vishnu Soni", category: "Networking", points: 0, status: "upcoming", date: "Jul 11, 2026", time: "4:00 PM – 6:30 PM" },
      { name: "Coffee With Business", category: "Networking", points: 0, status: "upcoming", date: "Jul 13, 2026", time: "6:00 PM" },
    ],
  },
  {
    week: 3,
    dates: "Jul 15 – Jul 21",
    theme: "RISE TO THE TOP",
    description: "Intensify the competition and push beyond limits.",
    events: [
      { name: "In-Chapter 121 Conclave", category: "121", points: 0, status: "completed", date: "Jul 15, 2026" },
      { name: "Box Cricket Match – vs BNI Faustus", category: "Fun & Games", points: 0, status: "completed", date: "Jul 17, 2026" },
      { name: "Know Your Members – Harsh Brambhatt", category: "Networking", points: 0, status: "completed", date: "Jul 18, 2026" },
    ],
  },
  {
    week: 4,
    dates: "Jul 22 – Jul 29",
    theme: "THE FINAL BATTLE",
    description: "Everything is on the line. Champions are made in the final stretch.",
    events: [
      { name: "Sports Event", category: "Fun & Games", points: 0, status: "upcoming", date: "Jul 24, 2026", time: "8:30 PM onwards" },
      { name: "Coffee With Business", category: "Networking", points: 0, status: "upcoming", date: "Jul 27, 2026", time: "6:00 PM" },
    ],
  },
];

export const scheduleEvents: ScheduleEvent[] = weeklyEvents.flatMap((w) => w.events);

export const specialEvents: SpecialEvent[] = [
  {
    name: "Cross Chapter Meet",
    desc: "Week 2 networking session connecting members across chapters.",
    date: "Jul 09, 2026",
    time: "4:00 PM – 6:00 PM",
    venue: "Grill Kitchen, Prahladnagar",
    status: "upcoming",
  },
  {
    name: "Sports Event",
    desc: "Week 2 fun & games night for all four teams.",
    date: "Jul 10, 2026",
    time: "8:30 PM onwards",
    status: "upcoming",
  },
  {
    name: "Know Your Members – Adv. Jay Patel & Vishnu Soni",
    desc: "Week 2 networking session spotlighting two team owners.",
    date: "Jul 11, 2026",
    time: "4:00 PM – 6:30 PM",
    status: "upcoming",
  },
  {
    name: "Coffee With Business",
    desc: "Week 2 networking session over coffee and business talk.",
    date: "Jul 13, 2026",
    time: "6:00 PM",
    status: "upcoming",
  },
  {
    name: "In-Chapter 121 Conclave",
    desc: "Week 2 in-chapter one-to-one conclave for deeper connections.",
    date: "Jul 15, 2026",
    time: "After Meeting",
    status: "upcoming",
  },
];

export const partners: Partner[] = [
  { name: "Jukebox Media", tier: "Presenting Sponsor", tagline: "Presenting Sponsor", logo: "/images/jukebox-media-logo.png" },
  { name: "Chahana Dental Studio", tier: "Dental Sponsor", tagline: "Dental Sponsor", logo: "/images/roster/chahana-dental-logo.png" },
  { name: "Prihaan Spices", tier: "Gifting Sponsor", tagline: "Gifting Sponsor", logo: "/images/partners/prihaan-spices-logo.png" },
  { name: "Destination Anywhere", tier: "Travel Sponsor", tagline: "Travel Sponsor", logo: "/images/partners/destination-anywhere-logo.png" },
  { name: "Fitness Hustler", tier: "Fitness Sponsor", tagline: "Fitness Sponsor", logo: "/images/partners/fitness-hustler-logo.png" },
  { name: "Gravity Media Marketing", tier: "Web Development", tagline: "Web Development Partner", logo: "/images/partners/gravity-media-logo.png" },
];

export const topPerformers: { label: string; name?: string; image?: string; team?: string; value?: string }[] = [
  { label: "MVP", name: "Jigar R Shah", image: "/images/roster/jigar-shah.png", team: "Silver Spoon Warriors", value: "12,230 pts" },
  { label: "Max Referrer", name: "Jimil Shah", image: "/images/roster/jimil-shah.png", team: "CSM Diplomats", value: "750 pts" },
  { label: "Max TYFCB", name: "Jigar R Shah", image: "/images/roster/jigar-shah.png", team: "Silver Spoon Warriors", value: "10,800 pts" },
  { label: "Max 121", name: "Ankit Jani", image: "/images/roster/ankit-jani.png", team: "VAER Strategists", value: "440 pts" },
];

export const blogCategories: string[] = ["Strategy", "Leadership", "Networking", "Execution", "Business Growth", "Nation Building"];

export const blogPosts: BlogPost[] = [
  {
    id: "power-of-strategic-collaboration",
    title: "The Power of Strategic Collaboration",
    excerpt: "How strategic partnerships create exponential value in business and beyond. Discover why the most successful businesses in ABL 2026 are the ones that master the art of collaboration.",
    author: "Team Modi",
    date: "May 29, 2026",
    readTime: "4 min read",
    category: "Strategy",
    image: "/images/blog-strategy.png",
  },
  {
    id: "leadership-in-the-arena",
    title: "Leadership in the Arena: Key Takeaways",
    excerpt: "Lessons from Week 1 that are shaping the champions of tomorrow. How decisive leadership under pressure is the defining trait of top performers this season.",
    author: "Team Doval",
    date: "May 27, 2026",
    readTime: "5 min read",
    category: "Leadership",
    image: "/images/blog_leadership.png",
  },
  {
    id: "building-connections",
    title: "Building Connections, Building the Nation",
    excerpt: "Every referral, every meeting, every connection counts towards a greater purpose. This week's challenge is showing us how business relationships fuel national growth.",
    author: "Team Jaishankar",
    date: "May 25, 2026",
    readTime: "3 min read",
    category: "Networking",
    image: "/images/blog-networking.png",
  },
  {
    id: "execution-is-everything",
    title: "Execution is Everything: Week 2 Insights",
    excerpt: "Strategy is nothing without execution. Our warriors are proving that discipline, consistency, and relentless action separate the good from the legendary.",
    author: "Team Amit Shah",
    date: "May 24, 2026",
    readTime: "4 min read",
    category: "Execution",
    image: "/images/blog-growth.png",
  },
];

export const tournamentRules: RuleSection[] = [
  {
    section: "Scoring System",
    rules: [
      "Business Growth (TYFCB): Up to 300 points per week",
      "Referrals Generated: Up to 250 points per week",
      "Meetings Conducted: Up to 200 points per week",
      "One-to-Ones: Up to 150 points per week",
      "Event Participation: Up to 100 points per week",
      "Maximum 1,000 core points per week",
    ],
  },
  {
    section: "Bonus Points",
    rules: [
      "Early Bird Bonus: +25 points (complete events before deadline)",
      "Perfect Week Bonus: +100 points (complete all events in a week)",
      "Consistency Bonus: +75 points (participate in 5+ consecutive events)",
      "Mega Impact Bonus: +150 points (generate high business impact)",
      "Maximum 350 bonus points per week",
    ],
  },
  {
    section: "Deductions",
    rules: [
      "No Show: -25 points (missed event without notice)",
      "Late Submission: -15 points (submitted after deadline)",
      "Incomplete Activity: -10 points (did not meet event requirements)",
    ],
  },
  {
    section: "Eligibility",
    rules: [
      "All participants must be active BNI members",
      "Each team has 7-8 business owners",
      "Participants must attend minimum 75% of events",
      "Business data must be verified by chapter leadership",
    ],
  },
  {
    section: "Tournament Format",
    rules: [
      "Duration: July 1st to July 29th, 2026 (4 weeks)",
      "Weekly themes guide each week's challenges",
      "Leaderboard updated every Wednesday at 8:00 PM",
      "Final standings determine the champion",
    ],
  },
  {
    section: "Prize & Recognition",
    rules: [
      "Winning team owner receives 1.5x prize pool",
      "Individual MVP awards for top performers",
      "Team trophies for champion and runner-up",
      "Permanent Wall of Fame recognition",
    ],
  },
];
